package vista.Admin;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;

import modelo.Episodio;
import modelo.Serie;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class VerInfoSerieAdmin extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Variables declaration - do not modify                     
    private javax.swing.JButton botonBorrarEpisodio;
    private javax.swing.JButton botonPersonaje;
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JButton botonModificarEpisodio;
    private javax.swing.JButton botonNuevoEpisodio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelSinopsis;
    private javax.swing.JTextArea textoSinopsis;
    private javax.swing.JTextArea tipoGenero;
    // End of variables declaration                   

	
    /**
     * Creates new form VerInfoSerieAdmin
     */
    public VerInfoSerieAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tipoGenero = new javax.swing.JTextArea();
        labelSinopsis = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoSinopsis = new javax.swing.JTextArea();
        botonGuardarCambios = new javax.swing.JButton();
        this.botonGuardarCambios.setActionCommand("guardar");
        botonPersonaje = new javax.swing.JButton();
        this.botonPersonaje.setActionCommand("personaje");
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonModificarEpisodio = new javax.swing.JButton();
        botonBorrarEpisodio = new javax.swing.JButton();
        botonNuevoEpisodio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelTitulo.setText("titulo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Genero");

        tipoGenero.setColumns(20);
        tipoGenero.setRows(5);
        jScrollPane2.setViewportView(tipoGenero);

        labelSinopsis.setText("Sinopsis");

        textoSinopsis.setColumns(20);
        textoSinopsis.setRows(5);
        jScrollPane3.setViewportView(textoSinopsis);

        botonGuardarCambios.setText("Guardar cambios");

        botonPersonaje.setText("Añadir personaje-actor");

        jLabel2.setText("Episodios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        botonModificarEpisodio.setText("Modificar episodio");
        botonModificarEpisodio.setActionCommand("modificarEpisodio");

        botonBorrarEpisodio.setText("Borrar episodio");
        botonBorrarEpisodio.setActionCommand("borrarEpisodio");
        
        botonNuevoEpisodio.setText("Nuevo episodio");
        botonNuevoEpisodio.setActionCommand("nuevoEpisodio");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSinopsis)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(32, 32, 32)
                                        .addComponent(jScrollPane2))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(botonGuardarCambios)
                                        .addGap(84, 84, 84)
                                        .addComponent(botonPersonaje)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonNuevoEpisodio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(botonModificarEpisodio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonBorrarEpisodio))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(labelSinopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonModificarEpisodio)
                            .addComponent(botonBorrarEpisodio)
                            .addComponent(botonNuevoEpisodio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuardarCambios)
                            .addComponent(botonPersonaje))
                        .addGap(36, 36, 36))))
        );
        
        pack();
    }// </editor-fold>                        



	public void updateVista(Serie serie) {
    	this.labelTitulo.setText(serie.toString());
    	this.textoSinopsis.setText(serie.getSinopsis());
    	//this.tipoGenero.setText(serie.getGenero());
    	this.jTextArea1.setText(serie.getTitular());
		
	}

	public String getSinopsis(){
		return this.textoSinopsis.getText();
	}
	
	public void updateGenero(String cadena){
		this.tipoGenero.setText(cadena);
	}
	
	public void addActionListener(ActionListener al) {
		// TODO Auto-generated method stub
		this.botonGuardarCambios.addActionListener(al);
		this.botonPersonaje.addActionListener(al);
		this.botonBorrarEpisodio.addActionListener(al);
		this.botonModificarEpisodio.addActionListener(al);
		this.botonNuevoEpisodio.addActionListener(al);
		
	}

	public void setEpisodios(ArrayList<Episodio> lista){
	    
    	Object[][] obj = new Object[lista.size()][4];
    	jTable1.setModel(new javax.swing.table.DefaultTableModel(
               obj,
                new String [] {
                    "Num", "Temp", "Titulo", "Fecha"
                }
            ));
    	Iterator<Episodio> it = lista.iterator();
    	String[][] info = new String[lista.size()][4];
    	int i = 0;
    	
    	while(it.hasNext()){
    		Episodio epi = it.next();
    		info[i][0] = epi.getNumOrden().toString();
    		this.jTable1.setValueAt(info[i][0], i, 0);
    		info[i][1] = epi.getNumTemporada().toString();
    		this.jTable1.setValueAt(info[i][1], i, 1);
    		info[i][2] = epi.toString();
    		this.jTable1.setValueAt(epi, i, 2);
    		info[i][3] = epi.getEstreno().toString();
    		this.jTable1.setValueAt(info[i][3], i, 3);
    		i++;
    	}

    }
	
    public Episodio getSelectedEpisodio(){
    	Episodio episodio = null;
    	episodio = (Episodio) this.jTable1.getValueAt(
    			this.jTable1.getSelectedRow(), 2);
    	return episodio;
    }
    
	public String getTitular() {
		// TODO Auto-generated method stub
		return this.jTextArea1.getText();
	}

	public String getGenero() {
		// TODO Auto-generated method stub
		return this.tipoGenero.getText();
	}
}
