package vista.Admin;

import java.awt.event.ActionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class VistaNuevaSerieAdmin extends javax.swing.JFrame {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Variables declaration - do not modify                     
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JLabel labelEstreno;
    private javax.swing.JLabel labelFinalizacion;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelSinopsis;
    private javax.swing.JLabel labelTitular;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textoEstreno;
    private javax.swing.JTextField textoFinalizacion;
    private javax.swing.JTextField textoGenero;
    private javax.swing.JTextField textoSinopsis;
    private javax.swing.JTextField textoTitular;
    private javax.swing.JTextField textoTitulo;
	
	
    /**
     * Creates new form VistaNuevaSerieAdmin
     */
    public VistaNuevaSerieAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	this.setTitle("Nueva Serie");

        labelTitulo = new javax.swing.JLabel();
        textoTitulo = new javax.swing.JTextField();
        labelTitular = new javax.swing.JLabel();
        textoTitular = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        labelSinopsis = new javax.swing.JLabel();
        labelEstreno = new javax.swing.JLabel();
        labelFinalizacion = new javax.swing.JLabel();
        textoGenero = new javax.swing.JTextField();
        textoSinopsis = new javax.swing.JTextField();
        textoEstreno = new javax.swing.JTextField();
        textoFinalizacion = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();
        botonCrear.setActionCommand("crear");
        botonCancelar = new javax.swing.JButton();

        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setText("Titulo:");

        textoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTituloActionPerformed(evt);
            }
        });

        labelTitular.setText("Titular:");

        textoTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTitularActionPerformed(evt);
            }
        });

        labelGenero.setText("Genero:");

        labelSinopsis.setText("Sinopsis:");

        labelEstreno.setText("Estreno:");

        labelFinalizacion.setText("Finalizacion");

        textoGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoGeneroActionPerformed(evt);
            }
        });

        textoSinopsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSinopsisActionPerformed(evt);
            }
        });

        textoEstreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstrenoActionPerformed(evt);
            }
        });

        textoFinalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFinalizacionActionPerformed(evt);
            }
        });

        botonCrear.setText("Crear");

        botonCancelar.setText("Cancelar");
        botonCancelar.setActionCommand("cancelar");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFinalizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(textoFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSinopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEstreno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonCancelar, botonCrear});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitular)
                    .addComponent(textoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGenero)
                    .addComponent(textoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSinopsis)
                    .addComponent(textoSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstreno)
                    .addComponent(textoEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFinalizacion)
                    .addComponent(textoFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCrear)
                    .addComponent(botonCancelar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void textoTituloActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code helre:
    }                                           

    private void textoTitularActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textoGeneroActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void textoSinopsisActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void textoEstrenoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textoFinalizacionActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

	public String getTextoEstreno() {
		return textoEstreno.getText();
	}

	public void setTextoEstreno(javax.swing.JTextField textoEstreno) {
		this.textoEstreno = textoEstreno;
	}

	public String getTextoFinalizacion() {
		return textoFinalizacion.getText();
	}

	public void setTextoFinalizacion(javax.swing.JTextField textoFinalizacion) {
		this.textoFinalizacion = textoFinalizacion;
	}

	public String getTextoGenero() {
		return textoGenero.getText();
	}

	public void setTextoGenero(javax.swing.JTextField textoGenero) {
		this.textoGenero = textoGenero;
	}

	public String getTextoSinopsis() {
		return textoSinopsis.getText();
	}

	public void setTextoSinopsis(javax.swing.JTextField textoSinopsis) {
		this.textoSinopsis = textoSinopsis;
	}

	public String getTextoTitular() {
		return textoTitular.getText();
	}

	public void setTextoTitular(javax.swing.JTextField textoTitular) {
		this.textoTitular = textoTitular;
	}

	public String getTextoTitulo() {
		return textoTitulo.getText();
	}

	public void setTextoTitulo(javax.swing.JTextField textoTitulo) {
		this.textoTitulo = textoTitulo;
	}

	public void setActionListener(ActionListener al) {
		// TODO Auto-generated method stub
		this.botonCrear.addActionListener(al);
		this.botonCancelar.addActionListener(al);
		
	}                       
	
	
}
