package vista.Admin;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.DefaultListModel;

import modelo.Actor;
import modelo.Personaje;
import modelo.Serie;

public class VistaPersonajeActor extends javax.swing.JFrame {

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaActores;
    private javax.swing.JList listaPersonajes;
    // End of variables declaration   
	
    /**
     * Creates new form ActorPersonajeEpisodio
     */
    public VistaPersonajeActor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaActores = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPersonajes = new javax.swing.JList();
        botonAceptar = new javax.swing.JButton();
        botonAceptar.setActionCommand("aceptar");
        botonCancelar = new javax.swing.JButton();
        botonCancelar.setActionCommand("cancelar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione un actor:");

        listaActores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaActores);

        jLabel2.setText("Seleccione un personaje:");

        listaPersonajes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaPersonajes);

        botonAceptar.setText("Aceptar");
        botonAceptar.setActionCommand("aceptar");
        
        botonCancelar.setText("Cancelar");
        botonCancelar.setActionCommand("cancelar");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(botonCancelar)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>                        
    
	public void muestraPersonajes(ArrayList<Personaje> lista){
		this.listaPersonajes.removeAll();
		Iterator<Personaje> it = lista.iterator();
		DefaultListModel modelo = new DefaultListModel();
		while(it.hasNext()){
			Personaje person = it.next();
			modelo.addElement(person);
		}
		this.listaPersonajes.setModel(modelo);
	}
	public Object getSelectedPersonaje(){
		return this.listaPersonajes.getSelectedValue();
	}
    
	public void muestraActores(ArrayList<Actor> lista){
		this.listaActores.removeAll();
		Iterator<Actor> it = lista.iterator();
		DefaultListModel modelo = new DefaultListModel();
		while(it.hasNext()){
			Actor actor = it.next();
			modelo.addElement(actor);
		}
		this.listaActores.setModel(modelo);
	}
	public Object getSelectedActor(){
		return this.listaActores.getSelectedValue();
	}

	public void setActionListener(ActionListener al){
		this.botonAceptar.addActionListener(al);
		this.botonCancelar.addActionListener(al);
	}


                
}
