package vista.User;

import java.awt.event.ActionListener;
import java.util.ArrayList;


import java.util.Iterator;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.text.Document;

import modelo.ComentarioSerie;
import modelo.Episodio;


/**
 *
 * @author Alex
 */
public class VistaSerieUser extends javax.swing.JFrame {
private static final long serialVersionUID = 1L;
	/* Creates new form VistaSerie
     */
    public VistaSerieUser() {
    	setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    	/*
    	this.addWindowListener(new WindowAction(){
    		public void windowClosing(ActionEvent ev){
    			dispose();
    		}
    	});*/

        initComponents();
        
		
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param serie Serie con la informacion a mostrar en la ventana
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	

    	
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tituloSerie = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titularText = new javax.swing.JTextArea();
        Genero = new javax.swing.JLabel();
        tipoGenero = new javax.swing.JLabel();
        sinopsis = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sinopsisText = new javax.swing.JTextArea();
        episodios = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaEpisodios = new javax.swing.JTable();
        infoEpisodio = new javax.swing.JButton();
        seguirSerie = new javax.swing.JButton();
        votos1 = new javax.swing.JLabel();
        nota = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        botonVotar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        areaComentarios = new javax.swing.JTextPane();
        cerrar = new javax.swing.JButton();
        cerrar.setActionCommand("cerrar");
   
        anadirComentario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        comentarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloSerie.setText("");

        titularText.setColumns(20);
        titularText.setRows(5);
        jScrollPane1.setViewportView(titularText);

        Genero.setText("Genero: ");

        tipoGenero.setText("");

        sinopsis.setText("Sinopsis");

        sinopsisText.setColumns(20);
        sinopsisText.setRows(5);
        sinopsisText.setText("");
        jScrollPane2.setViewportView(sinopsisText);

        episodios.setText("Episodios");

        tablaEpisodios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Num", "Temp", "Titulo", "Fecha"
            }
        ));
        jScrollPane5.setViewportView(tablaEpisodios);

        infoEpisodio.setText("infoEpisodio");
        infoEpisodio.setActionCommand("infoEpisodio");

        seguirSerie.setText("Seguir");
        seguirSerie.setActionCommand("seguidor");

        votos1.setText("Nota media de votos");

        nota.setText("nota");

        jSlider1.setMaximum(10);
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setPaintTicks(true);
        jSlider1.setPaintLabels(true);

        botonVotar.setText("votar");
        botonVotar.setActionCommand("votar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(botonVotar))
                            .addComponent(tituloSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(sinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(episodios)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(votos1)
                                .addGap(45, 45, 45)
                                .addComponent(nota, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Genero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seguirSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(infoEpisodio)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tituloSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(votos1)
                    .addComponent(nota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genero)
                    .addComponent(tipoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sinopsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(episodios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonVotar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seguirSerie)
                    .addComponent(infoEpisodio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(areaComentarios);

        cerrar.setText("cerrar");

        anadirComentario.setText("anadir aqui el comentario");

        jButton1.setText("anadirComentario");
        jButton1.setActionCommand("comentar");

        comentarios.setText("Comentarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comentarios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(anadirComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cerrar)
                            .addComponent(jButton1))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(comentarios)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(anadirComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Genero;
    private javax.swing.JTextPane areaComentarios;
    private javax.swing.JTextField anadirComentario;
    private javax.swing.JButton botonVotar;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel comentarios;
    private javax.swing.JLabel episodios;
    private javax.swing.JButton infoEpisodio;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tablaEpisodios;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea titularText;
    private javax.swing.JTextArea sinopsisText;
    private javax.swing.JLabel nota;
    private javax.swing.JButton seguirSerie;
    private javax.swing.JLabel sinopsis;
    private javax.swing.JLabel tipoGenero;
    private javax.swing.JLabel tituloSerie;
    private javax.swing.JLabel votos1;

    // End of variables declaration                 
    
    public String getSeguidor(){
    	return this.seguirSerie.getText();
    	
    }
    
    public int getCalificacion(){
    	return this.jSlider1.getValue();
    }
    
    public void setSeguidorText(String string){
    	this.seguirSerie.setText(string);

    }
    
    public void updateVista(String titulo, String sinop, String titular){
    	this.tituloSerie.setText(titulo);
    	this.sinopsisText.setText(sinop);
    	this.titularText.setText(titular);
    	
    }
    
    public void updateGeneros(String cadena){
    	this.tipoGenero.setText(cadena);
    }
    
    public void setEpisodios(ArrayList<Episodio> lista){
    
    	Object[][] obj = new Object[lista.size()][4];
        tablaEpisodios.setModel(new javax.swing.table.DefaultTableModel(
               obj,
                new String [] {
                    "Num", "Temp", "Titulo", "Fecha"
                }
            ));
    	
    	Iterator<Episodio> it = lista.iterator();
    	String[][] info = new String[lista.size()][4];
    	int i = 0;
    	
    	while(it.hasNext()){
    		Episodio epi = it.next();
    		info[i][0] = epi.getNumOrden().toString();
    		this.tablaEpisodios.setValueAt(info[i][0], i, 0);
    		info[i][1] = epi.getNumTemporada().toString();
    		this.tablaEpisodios.setValueAt(info[i][1], i, 1);
    		info[i][2] = epi.toString();
    		this.tablaEpisodios.setValueAt(epi, i, 2);
    		info[i][3] = epi.getEstreno().toString();
    		this.tablaEpisodios.setValueAt(info[i][3], i, 3);
    		i++;
    	}

    }
    
    public Episodio getSelectedEpisodio(){
    	Episodio episodio = null;
    	episodio = (Episodio) this.tablaEpisodios.getValueAt(
    			this.tablaEpisodios.getSelectedRow(), 2);
    	return episodio;
    }
    
    public void addListener(ActionListener al){
		this.cerrar.addActionListener(al);
		this.seguirSerie.addActionListener(al);
		this.infoEpisodio.addActionListener(al);
		this.botonVotar.addActionListener(al);
		this.jButton1.addActionListener(al);
		
	}

	public void setNotaMedia(Double nota2) {
		this.nota.setText(nota2.toString());
		
	}
	public String getComentario(){
		return this.anadirComentario.getText();
	}
	
	public void publicaComentarios(ArrayList<ComentarioSerie> comentarios){
		Iterator<ComentarioSerie> it = comentarios.iterator();
		this.areaComentarios.removeAll();
	        Document doc = this.areaComentarios.getDocument();
	        for (ComentarioSerie s : comentarios)
	            try {
	                doc.insertString(doc.getLength(), "Autor: " + s.getNick() +
	                		"\nFecha: " + s.getFecha().toString() + "\n" + s.getTexto() + "\n\n", null);
	            } catch (Exception e) {
	                e.printStackTrace();
	            }
			//label.setText(comment.getTexto());
			//this.areaComentarios.add(label);
		
	}
}

