
package vista.User;

import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;

import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class VistaModificarDatosUsuario extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form VistaNuevoUsuario
     */
    public VistaModificarDatosUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        //nick = new javax.swing.JLabel();
        //jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        seleccionarImagen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Contraseña");

        jPasswordField1.setText("password");

        jLabel3.setText("Imagen avatar");

        seleccionarImagen.setText("Selecciona imagen");
        seleccionarImagen.setActionCommand("imagen");

        jLabel4.setText("Fecha nacimiento");

        fechaNacimiento.setText("dia/mes/año");

       aceptar.setActionCommand("aceptar");
       aceptar.setText("aceptar");
       cancelar.setText("cancelar");
       setTitle("Modificar datos usuario");
       //nick.setText("nick");

        cancelar.setActionCommand("cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seleccionarImagen)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(cancelar)
                        .addGap(106, 106, 106))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
               
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(seleccionarImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
     
    
    public void usuarioYaCreado() {
		JOptionPane.showMessageDialog(null,  "Usuario ya creado","", JOptionPane.INFORMATION_MESSAGE);
	}
    
    public void nuevoUsuario() {
		JOptionPane.showMessageDialog(null,  "Nuevo usuario creado","", JOptionPane.INFORMATION_MESSAGE);
	}
    
    public void cerrar(){
		this.dispose();
		//this.frame.setVisible(false);
	}
    
    
    public void addLoginListener(ActionListener al){
		this.aceptar.addActionListener(al);
		this.cancelar.addActionListener(al);
		this.seleccionarImagen.addActionListener(al);
	}

    // Variables declaration - do not modify                     
    private javax.swing.JButton seleccionarImagen;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private FileInputStream is;
    private File f;
    
    public String getPasswordField() {
		return new String(jPasswordField1.getPassword());
	}

	public void setjPasswordField1(javax.swing.JPasswordField jPasswordField1) {
		this.jPasswordField1 = jPasswordField1;
	}

	public String getFecha() {
		return fechaNacimiento.getText();
	}

	public void setfechaNacimiento(javax.swing.JTextField fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField fechaNacimiento;
    // End of variables declaration                   
	public void addActionListener(ActionListener al) {
		// TODO Auto-generated method stub
		this.aceptar.addActionListener(al);
		this.cancelar.addActionListener(al);
		this.seleccionarImagen.addActionListener(al);
		
	}

	public void setFile(File file) {
		// TODO Auto-generated method stub
		this.f = file;
	}
	public File getFile(){
		return this.f;
	}
	

	public void setFileInputStream(FileInputStream is) {
		this.is=is;
	}
	public FileInputStream getFileInputStream(){
		return this.is;
	}
}
